  # config/MemLoTrack/_mixin/anti_uav_train.yaml

  # ── TRAIN Phase: Add data cleaning filters ──
  - path: "run.data.train.source.parameters.filters"
    value:
      # 1) annotation_standard -> already input as XYXY, so process as XYXY
      - type: "data_cleaning.annotation_standard"
        parameters:
          bounding_box_format: "XYXY"
          bounding_box_coordinate_system: "Continuous"
      # 2) bounding_box -> remove invalid boxes (zero size, etc.)
      - type: "data_cleaning.bounding_box"
        parameters:
          fit_in_image_size: true
          update_validity: true
          remove_invalid_objects: true
          remove_empty_objects: true
      # 3) integrity -> remove frames/videos without annotations
      - type: "data_cleaning.integrity"
        parameters:
          remove_zero_annotation_objects: true
          remove_zero_annotation_image: true
          remove_zero_annotation_video_head_tail: true
          remove_invalid_image: true

  # ── TRAIN Phase: Define actual datasets to use ──
  - path: "run.data.train.source.parameters.datasets"
    value:
      # - name: "Anti_UAV_300_VIS"
      #   type: "SOT"
      #   splits: "train"
      # - name: "Anti_UAV_300_IR"
      #   type: "SOT"
      #   splits: "train"
      - name: "Anti_UAV_410"
        type: "SOT"
        splits: "train"
      # - name: "DUT_Detection"
      #   type: "DET"
      #   splits: "train"


